### ISSUE TITLE
Runtime error while running Carla simulator version 0.9.5 with python 3.7

### ISSUE THREAD

**Issue by AdoniaMbarebaki** [AdoniaMbarebaki/Collision-avoidance-system-in-carla-v-0.9.5#1]
Use tf.cast instead.
  0%|                                                                       | 4/10000 [01:10<57:16:55, 20.63s/episodes]ERROR: failed to destroy actor 136 : time-out of 6000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000
ERROR: failed to destroy actor 137 : time-out of 6000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000
ERROR: failed to destroy actor 138 : time-out of 6000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000
  0%|                                                                       | 5/10000 [01:49<72:34:01, 26.14s/episodes]Traceback (most recent call last):
  File "RL_CNN.py", line 332, in <module>
    current_state = env.reset()
  File "RL_CNN.py", line 107, in reset
    self.transform = random.choice(self.world.get_map().get_spawn_points())
RuntimeError: time-out of 6000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000
  0%|                                                                       | 5/10000 [02:14<74:39:09, 26.89s/episodes]

**Comment by XuChang-c** [comment]
when i run it in gpu,  i found 'Error in `/....../carla5/bin/python': free(): invalid pointer: 0x00007f482ea666e0',
